backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to main)

## This line should *not* be indented
##By default, saving a post in the CMS interface pushes a commit directly to the publication branch specified in backend. However, you also have the option to enable the Editorial Workflow, which adds an interface for drafting, reviewing, and approving posts. To do this, add the following line to your Netlify CMS config.yml:
#publish_mode: editorial_workflow

media_folder: "/public/assets/blog" # Media files will be stored in the repo under /public/assets/blog
public_folder: "/assets/blog" # The src attribute for uploaded media will begin with /assets/blog


collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: 
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Author", name: "author", widget: "string"}
      - { label: "Tags", name: "tags", widget: "list", default: ["post"]}
      - { label: "Date", name: "date", widget: "datetime"}
      - { label: "Description", name: "description", widget: "markdown"}
      - { label: "Body", name: "body", widget: "markdown"}

